name: kha256
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=2.20.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - scipy>=1.7.0
  - jupyterlab
  - nodejs
  - pip:
    - kececinumbers==0.8.4
    - kha256
    - ipywidgets
    - plotly
    - seaborn
